// Generated by Classiq.
// Classiq version: 0.105.0
// Creation timestamp: 2026-01-31T20:42:36.409780+00:00
// Random seed: 3699882668

OPENQASM 2.0;
include "qelib1.inc";
gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_0 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__gray_code_y q0,q1 {
  ry(1.6449729026109838) q1;
  cx q0,q1;
  ry(0.8577628853343217) q1;
  cx q0,q1;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__gray_code_y q6,q5;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_2 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_0 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_2 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_4 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__gray_code_y q0,q1,q2 {
  ry(1.6603425548225998) q2;
  cx q0,q2;
  ry(0.5326134544681902) q2;
  cx q1,q2;
  ry(0.11563769274827929) q2;
  cx q0,q2;
  ry(0.26128098170715497) q2;
  cx q1,q2;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__gray_code_y q6,q5,q4;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_6 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_4 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_6 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_8 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__gray_code_y q0,q1,q2,q3 {
  ry(1.6432189164669937) q3;
  cx q0,q3;
  ry(0.3043010496223923) q3;
  cx q1,q3;
  ry(0.08217424719396255) q3;
  cx q0,q3;
  ry(0.16172956890695667) q3;
  cx q2,q3;
  ry(0.01965744449468987) q3;
  cx q0,q3;
  ry(0.008374134917451148) q3;
  cx q1,q3;
  ry(0.04046102670055632) q3;
  cx q0,q3;
  ry(0.08112568845740736) q3;
  cx q2,q3;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__gray_code_y q6,q5,q4,q3;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_10 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_8 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_10 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_12 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__gray_code_y q0,q1,q2,q3,q4 {
  ry(1.6137163505001582) q4;
  cx q0,q4;
  ry(0.1603526581543721) q4;
  cx q1,q4;
  ry(0.04719920460987878) q4;
  cx q0,q4;
  ry(0.08792696346942412) q4;
  cx q2,q4;
  ry(0.013468252525389107) q4;
  cx q0,q4;
  ry(0.007913106790239405) q4;
  cx q1,q4;
  ry(0.024251105160901412) q4;
  cx q0,q4;
  ry(0.045047495789965294) q4;
  cx q3,q4;
  ry(0.003442418841041184) q4;
  cx q0,q4;
  ry(0.002003716982852788) q4;
  cx q1,q4;
  ry(0.0006382508670463583) q4;
  cx q0,q4;
  ry(0.0010748301102083968) q4;
  cx q2,q4;
  ry(0.0067619598958830185) q4;
  cx q0,q4;
  ry(0.0039642534062257345) q4;
  cx q1,q4;
  ry(0.012196805260092453) q4;
  cx q0,q4;
  ry(0.02265211974053266) q4;
  cx q3,q4;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__gray_code_y q6,q5,q4,q3,q2;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_14 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_12 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_14 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_16 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__gray_code_y q0,q1,q2,q3,q4,q5 {
  ry(1.5933311802528602) q5;
  cx q0,q5;
  ry(0.08144508938907172) q5;
  cx q1,q5;
  ry(0.024590799044252404) q5;
  cx q0,q5;
  ry(0.04507760711151398) q5;
  cx q2,q5;
  ry(0.007358141302371474) q5;
  cx q0,q5;
  ry(0.004592197560625934) q5;
  cx q1,q5;
  ry(0.012804627457268694) q5;
  cx q0,q5;
  ry(0.023263054329147485) q5;
  cx q3,q5;
  ry(0.001945590703580094) q5;
  cx q0,q5;
  ry(0.0012285425391718244) q5;
  cx q1,q5;
  ry(0.0005174800639335467) q5;
  cx q0,q5;
  ry(0.0007347788101477459) q5;
  cx q2,q5;
  ry(0.003721947340076609) q5;
  cx q0,q5;
  ry(0.002328634855603494) q5;
  cx q1,q5;
  ry(0.006472151582388369) q5;
  cx q0,q5;
  ry(0.011729954876809293) q5;
  cx q4,q5;
  ry(0.0004935492331678698) q5;
  cx q0,q5;
  ry(0.00031255026110085793) q5;
  cx q1,q5;
  ry(0.00013192682893446023) q5;
  cx q0,q5;
  ry(0.00018697935800118803) q5;
  cx q2,q5;
  ry(4.300350385191831e-05) q5;
  cx q0,q5;
  ry(3.262557512281189e-05) q5;
  cx q1,q5;
  ry(7.008187143522221e-05) q5;
  cx q0,q5;
  ry(9.875122104834044e-05) q5;
  cx q3,q5;
  ry(0.0009756593388317719) q5;
  cx q0,q5;
  ry(0.0006164384149325783) q5;
  cx q1,q5;
  ry(0.0002597597523553638) q5;
  cx q0,q5;
  ry(0.0003687013179296261) q5;
  cx q2,q5;
  ry(0.0018664279293757469) q5;
  cx q0,q5;
  ry(0.0011684510993555802) q5;
  cx q1,q5;
  ry(0.003244988155420389) q5;
  cx q0,q5;
  ry(0.005877523199340137) q5;
  cx q4,q5;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__gray_code_y q6,q5,q4,q3,q2,q1;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_18 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_16 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_18 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_20 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21__gray_code_y q0,q1,q2,q3,q4,q5,q6 {
  ry(1.582208366524006) q6;
  cx q0,q6;
  ry(0.04089163294375156) q6;
  cx q1,q6;
  ry(0.01242923177497875) q6;
  cx q0,q6;
  ry(0.02268813953440986) q6;
  cx q2,q6;
  ry(0.0037647778615314577) q6;
  cx q0,q6;
  ry(0.0023832862827986856) q6;
  cx q1,q6;
  ry(0.0064951675549287415) q6;
  cx q0,q6;
  ry(0.01173198359767548) q6;
  cx q3,q6;
  ry(0.0010046546501418126) q6;
  cx q0,q6;
  ry(0.0006464223566920654) q6;
  cx q1,q6;
  ry(0.00028722498224724446) q6;
  cx q0,q6;
  ry(0.00039575577131322273) q6;
  cx q2,q6;
  ry(0.001908331166071326) q6;
  cx q0,q6;
  ry(0.0012123797163497083) q6;
  cx q1,q6;
  ry(0.003287689064727966) q6;
  cx q0,q6;
  ry(0.0059203967378032955) q6;
  cx q4,q6;
  ry(0.0002558083730133283) q6;
  cx q0,q6;
  ry(0.00016537191647779392) q6;
  cx q1,q6;
  ry(7.399515583229183e-05) q6;
  cx q0,q6;
  ry(0.00010150261913012201) q6;
  cx q2,q6;
  ry(2.61275885191474e-05) q6;
  cx q0,q6;
  ry(2.0901835339121044e-05) q6;
  cx q1,q6;
  ry(4.036628541589232e-05) q6;
  cx q0,q6;
  ry(5.4707288263077664e-05) q6;
  cx q3,q6;
  ry(0.0005041964206794376) q6;
  cx q0,q6;
  ry(0.0003247277827308423) q6;
  cx q1,q6;
  ry(0.0001444948190248707) q6;
  cx q0,q6;
  ry(0.00019891073497761355) q6;
  cx q2,q6;
  ry(0.0009575476167022583) q6;
  cx q0,q6;
  ry(0.0006089060982119102) q6;
  cx q1,q6;
  ry(0.0016490537641341632) q6;
  cx q0,q6;
  ry(0.0029672260984274883) q6;
  cx q5,q6;
  ry(6.425580947376844e-05) q6;
  cx q0,q6;
  ry(4.159043605427709e-05) q6;
  cx q1,q6;
  ry(1.864369483593059e-05) q6;
  cx q0,q6;
  ry(2.5544719154797085e-05) q6;
  cx q2,q6;
  ry(6.590599601997288e-06) q6;
  cx q0,q6;
  ry(5.277828597188838e-06) q6;
  cx q1,q6;
  ry(1.017418346316995e-05) q6;
  cx q0,q6;
  ry(1.3772447470427468e-05) q6;
  cx q3,q6;
  ry(1.872651390278507e-06) q6;
  cx q0,q6;
  ry(1.5198008497738225e-06) q6;
  cx q1,q6;
  ry(8.844744188579723e-07) q6;
  cx q0,q6;
  ry(1.0351903749795943e-06) q6;
  cx q2,q6;
  ry(3.388216494763091e-06) q6;
  cx q0,q6;
  ry(2.7217680328636695e-06) q6;
  cx q1,q6;
  ry(5.217914298485948e-06) q6;
  cx q0,q6;
  ry(7.037749928339582e-06) q6;
  cx q4,q6;
  ry(0.00012802585991074714) q6;
  cx q0,q6;
  ry(8.278510931138128e-05) q6;
  cx q1,q6;
  ry(3.705565330939381e-05) q6;
  cx q0,q6;
  ry(5.081905849557353e-05) q6;
  cx q2,q6;
  ry(1.3087323631030129e-05) q6;
  cx q0,q6;
  ry(1.0471910607379176e-05) q6;
  cx q1,q6;
  ry(2.0216252864961592e-05) q6;
  cx q0,q6;
  ry(2.739196527757823e-05) q6;
  cx q3,q6;
  ry(0.0002523345152105512) q6;
  cx q0,q6;
  ry(0.00016255586526744276) q6;
  cx q1,q6;
  ry(7.235931106083782e-05) q6;
  cx q0,q6;
  ry(9.958623016658938e-05) q6;
  cx q2,q6;
  ry(0.00047920120162761246) q6;
  cx q0,q6;
  ry(0.00030479672691705734) q6;
  cx q1,q6;
  ry(0.0008251845505841716) q6;
  cx q0,q6;
  ry(0.0014844990335873935) q6;
  cx q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21__gray_code_y q6,q5,q4,q3,q2,q1,q0;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_22 q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23 q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_20 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_22 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code q0,q1,q2,q3,q4,q5,q6 {
  ry(1.5144101269772012) q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19 q0,q1,q2,q3,q4,q5,q6;
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23 q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code q0,q1,q2,q3,q4,q5,q6;
}

gate inplace_prepare_state__inplace_prepare_amplitudes q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes q0,q1,q2,q3,q4,q5,q6;
}

gate main__inplace_prepare_state q0,q1,q2,q3,q4,q5,q6 {
  inplace_prepare_state__inplace_prepare_amplitudes q0,q1,q2,q3,q4,q5,q6;
}

gate qft7 q0,q1,q2,q3,q4,q5,q6 {
  h q6;
  cp(pi/2) q6,q5;
  cp(pi/4) q6,q4;
  cp(pi/8) q6,q3;
  cp(pi/16) q6,q2;
  cp(pi/32) q6,q1;
  cp(pi/64) q6,q0;
  h q5;
  cp(pi/2) q5,q4;
  cp(pi/4) q5,q3;
  cp(pi/8) q5,q2;
  cp(pi/16) q5,q1;
  cp(pi/32) q5,q0;
  h q4;
  cp(pi/2) q4,q3;
  cp(pi/4) q4,q2;
  cp(pi/8) q4,q1;
  cp(pi/16) q4,q0;
  h q3;
  cp(pi/2) q3,q2;
  cp(pi/4) q3,q1;
  cp(pi/8) q3,q0;
  h q2;
  cp(pi/2) q2,q1;
  cp(pi/4) q2,q0;
  h q1;
  cp(pi/2) q1,q0;
  h q0;
}

gate qft7_dg_dg q0,q1,q2,q3,q4,q5,q6 {
  h q0;
  cp(-pi/2) q1,q0;
  h q1;
  cp(-pi/4) q2,q0;
  cp(-pi/2) q2,q1;
  h q2;
  cp(-pi/8) q3,q0;
  cp(-pi/4) q3,q1;
  cp(-pi/2) q3,q2;
  h q3;
  cp(-pi/16) q4,q0;
  cp(-pi/8) q4,q1;
  cp(-pi/4) q4,q2;
  cp(-pi/2) q4,q3;
  h q4;
  cp(-pi/32) q5,q0;
  cp(-pi/16) q5,q1;
  cp(-pi/8) q5,q2;
  cp(-pi/4) q5,q3;
  cp(-pi/2) q5,q4;
  h q5;
  cp(-pi/64) q6,q0;
  cp(-pi/32) q6,q1;
  cp(-pi/16) q6,q2;
  cp(-pi/8) q6,q3;
  cp(-pi/4) q6,q4;
  cp(-pi/2) q6,q5;
  h q6;
}

gate payoff__arithmetic__lessthan__subtractor_0__adder q0,q1,q2,q3,q4,q5,q6,q7 {
  qft7 q1,q2,q3,q4,q5,q6,q7;
  p(5.448699758569798) q7;
  p(4.614214209960008) q6;
  p(15*pi/16) q5;
  p(15*pi/8) q4;
  p(7*pi/4) q3;
  p(3*pi/2) q2;
  p(pi) q1;
  qft7_dg_dg q1,q2,q3,q4,q5,q6,q7;
}

gate payoff__arithmetic__lessthan__subtractor_0 q0,q1,q2,q3,q4,q5,q6,q7 {
  payoff__arithmetic__lessthan__subtractor_0__adder q0,q1,q2,q3,q4,q5,q6,q7;
}

gate payoff__arithmetic__lessthan__sign q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  cx q7,q8;
}

gate qft7_dg q0,q1,q2,q3,q4,q5,q6 {
  h q6;
  cp(pi/2) q6,q5;
  cp(pi/4) q6,q4;
  cp(pi/8) q6,q3;
  cp(pi/16) q6,q2;
  cp(pi/32) q6,q1;
  cp(pi/64) q6,q0;
  h q5;
  cp(pi/2) q5,q4;
  cp(pi/4) q5,q3;
  cp(pi/8) q5,q2;
  cp(pi/16) q5,q1;
  cp(pi/32) q5,q0;
  h q4;
  cp(pi/2) q4,q3;
  cp(pi/4) q4,q2;
  cp(pi/8) q4,q1;
  cp(pi/16) q4,q0;
  h q3;
  cp(pi/2) q3,q2;
  cp(pi/4) q3,q1;
  cp(pi/8) q3,q0;
  h q2;
  cp(pi/2) q2,q1;
  cp(pi/4) q2,q0;
  h q1;
  cp(pi/2) q1,q0;
  h q0;
}

gate qft7_dg_140038452605008 q0,q1,q2,q3,q4,q5,q6 {
  h q0;
  cp(-pi/2) q1,q0;
  h q1;
  cp(-pi/4) q2,q0;
  cp(-pi/2) q2,q1;
  h q2;
  cp(-pi/8) q3,q0;
  cp(-pi/4) q3,q1;
  cp(-pi/2) q3,q2;
  h q3;
  cp(-pi/16) q4,q0;
  cp(-pi/8) q4,q1;
  cp(-pi/4) q4,q2;
  cp(-pi/2) q4,q3;
  h q4;
  cp(-pi/32) q5,q0;
  cp(-pi/16) q5,q1;
  cp(-pi/8) q5,q2;
  cp(-pi/4) q5,q3;
  cp(-pi/2) q5,q4;
  h q5;
  cp(-pi/64) q6,q0;
  cp(-pi/32) q6,q1;
  cp(-pi/16) q6,q2;
  cp(-pi/8) q6,q3;
  cp(-pi/4) q6,q4;
  cp(-pi/2) q6,q5;
  h q6;
}

gate payoff__arithmetic__lessthan__subtractor_1__adder_qinverse q0,q1,q2,q3,q4,q5,q6,q7 {
  qft7_dg q1,q2,q3,q4,q5,q6,q7;
  p(-pi) q1;
  p(-3*pi/2) q2;
  p(-7*pi/4) q3;
  p(-15*pi/8) q4;
  p(-15*pi/16) q5;
  p(-4.614214209960008) q6;
  p(-5.448699758569798) q7;
  qft7_dg_140038452605008 q1,q2,q3,q4,q5,q6,q7;
}

gate payoff__arithmetic__lessthan__subtractor_1 q0,q1,q2,q3,q4,q5,q6,q7 {
  payoff__arithmetic__lessthan__subtractor_1__adder_qinverse q0,q1,q2,q3,q4,q5,q6,q7;
}

gate payoff__arithmetic__lessthan q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  payoff__arithmetic__lessthan__subtractor_0 q1,q2,q3,q4,q5,q6,q7,q8;
  payoff__arithmetic__lessthan__sign q1,q2,q3,q4,q5,q6,q7,q8,q0;
  payoff__arithmetic__lessthan__subtractor_1 q1,q2,q3,q4,q5,q6,q7,q8;
}

gate payoff__arithmetic q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  payoff__arithmetic__lessthan q0,q1,q2,q3,q4,q5,q6,q7,q8;
}

gate main__payoff q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  payoff__arithmetic q0,q1,q2,q3,q4,q5,q6,q7,q8;
}

qreg q[9];
main__inplace_prepare_state q[1],q[2],q[3],q[4],q[5],q[6],q[7];
main__payoff q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8];